### ISSUE TITLE
App creation scripts don't work

### ISSUE THREAD

**Issue by bgavrilMS** [Azure-Samples/ms-identity-aspnet-webapi-onbehalfof#30] opened 2021-01-19 16:11 UTC
Run Configure.ps1 with the old powershell. After providing a user, you get

```
Getting access from 'service' to 'Microsoft Graph'
Granted permissions.
Creating the AAD application (TodoListClient-OBO-sample-v2)
'liu.kang@bogavrilLTD.onmicrosoft.com' added as an application owner to app 'TodoListClient-OBO-sample-v2'
Done creating the client application (TodoListClient-OBO-sample-v2)
Getting access from 'client' to 'service'
Set-AzureADApplication : Error occurred while executing SetApplication
Code: Request_BadRequest
Message: Invalid value specified for property 'resourceAppId' of resource 'RequiredResourceAccess'.
RequestId: c5c253b8-ce02-4a76-b604-024ceb360673
DateTimeStamp: Tue, 19 Jan 2021 16:08:47 GMT
Details: PropertyName  - resourceAppId, PropertyErrorCode  - InvalidValue
HttpStatusCode: BadRequest
HttpStatusDescription: Bad Request
HttpResponseStatus: Completed
At C:\g\samples\ms-identity-aspnet-webapi-onbehalfof\AppCreationScripts\Configure.ps1:327 char:4
```

And with the new PowerShell (I have 7 RC1) you get: 

```
Connect-AzureAD: C:\g\samples\ms-identity-aspnet-webapi-onbehalfof\AppCreationScripts\Configure.ps1
Line |
 191 |             $creds = Connect-AzureAD -Credential $Credential -AzureEnvironmentName $azureEnvironmentName
     |                      ^ One or more errors occurred. (Could not load type
     | 'System.Security.Cryptography.SHA256Cng' from assembly 'System.Core, Version=4.0.0.0, Culture=neutral,
     | PublicKeyToken=b77a5c561934e089'.): Could not load type 'System.Security.Cryptography.SHA256Cng' from assembly
     | 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.
```

**Comment by aremo-ms** [comment] 2021-11-24 15:51
I cannot reproduce the issue. Closing. Feel free to contact me for more questions

**Closed by aremo-ms** 2021-11-24 15:51 UTC
Labels: bug
