### ISSUE TITLE
The request does not go through

### ISSUE THREAD

**Issue by ahmadizm** [Azure-Samples/ms-identity-aspnet-webapi-onbehalfof#6] opened 2019-07-31 21:02 UTC
The communication between the client app and the service is failing all the time for me. I followed the instructions, and am actually able to sign in. But when it comes to actually getting something from the service (Get method), the request is immediately returned without getting into the Get method. The error is Unauthorized, which is then shown to the user in the WPF client app.

![image](https://user-images.githubusercontent.com/43794127/62247719-05872300-b3ac-11e9-8299-011e2b6a3087.png)

I can make the Get method of the controller receive the request by removing the [Authorize] tag, which basically defeats my purpose, but shows that probably OWIN is not configured correctly in this sample. Even then, the claims are empty, and the controller check fails.

> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x ] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Follow the instructions for registering the apps and configuring the projects according to the instructions in this page. 

### Any log messages given by the failure
> The request is not received by the service. The response returns with "Unauthorized" error.

### Expected/desired behavior
>The request should be received by the controller method in the service. Currently, the only way for the controller to receive this request is removing the [Authorize] label from the controller. Even in that case, the claims are empty, and the controller check fails.

### OS and Version?
> Windows 10

### Versions
> 10.0.17763 Build 17763

### Mention any other details that might be useful
I followed all the instructions twice, and every time the same thing happened.
> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by TiagoBrenck** [comment] 2019-07-31 21:08
Hi @ahmadizm,

Can you double check that you followed this step: https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof#configure-authorized-client-applications-for-service-todolistservice-obo-sample-v2?

**Comment by ahmadizm** [comment] 2019-07-31 23:30
Do you mean the following settings? (I am only using the client app with the service, not the SPA)

![image](https://user-images.githubusercontent.com/43794127/62254889-88b27400-b3c0-11e9-99fa-61c7f74a7f1f.png)

![image](https://user-images.githubusercontent.com/43794127/62254943-c7e0c500-b3c0-11e9-9ec3-a6c71d7028d8.png)

Are we calling the downstream api at this stage (calling the service from the client with a GET request)? I am kind of new to this.

Thank you for getting back to me so quickly.

**Comment by TiagoBrenck** [comment] 2019-08-01 19:19
There was actually a not required step in the documentation, so I removed it. We don't need to add Authorized Clients since we are using `/.default` scope, and that will prompt the proper consents at the first login. If you want to keep having the Authorized Clients, you will need to click on **Grant admin consent for {your directory}** on the Web API application, **App Permissions** tab.

However this is not related to your problem and I actually couldn't reproduce it. So I advise you to delete your apps registrations and do it again. Pay extra attention when you are creating the `user_impersonation` scope and when you add it on the client app.

Let me know if you manage to make it work, so I can close this issue.
Thanks

**Comment by ahmadizm** [comment] 2019-08-01 20:24
Thank you, will do.

 In the meantime, I would like to mention one more thing: This app uses the following configuration on startup:

`app.UseWindowsAzureActiveDirectoryBearerAuthentication(
                new WindowsAzureActiveDirectoryBearerAuthenticationOptions
                {
                    Tenant = ConfigurationManager.AppSettings["ida:Tenant"],
                    //We set SaveSigninToken to true, to be able to retrieve the bearer token using the code: ClaimsPrincipal.Current.Identities.First().BootstrapContext
                    //This flag is mandatory for this flow to work
                    TokenValidationParameters = new TokenValidationParameters { SaveSigninToken = true, ValidAudience = ConfigurationManager.AppSettings["ida:Audience"] }
                });`

On the other hand, I have found another (working) sample [here](https://github.com/azureadquickstarts/appmodelv2-nativeclient-dotnet), where the startup has the following comment and code in its configuration:

`            // NOTE: The usual WindowsAzureActiveDirectoryBearerAuthentication middleware uses a
            // metadata endpoint which is not supported by the Microsoft identity platform endpoint.  Instead, this 
            // OpenIdConnectSecurityTokenProvider implementation can be used to fetch & use the OpenIdConnect
            // metadata document - which for the identity platform endpoint is https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration

            app.UseOAuthBearerAuthentication(new OAuthBearerAuthenticationOptions
            {
                AccessTokenFormat = new JwtFormat(
                    new TokenValidationParameters
                    {
                        // Check if the audience is intended to be this application
                        ValidAudiences = new [] { clientId, $"api://{clientId}" },

                        // Change below to 'true' if you want this Web API to accept tokens issued to one Azure AD tenant only (single-tenant)
                        // Note that this is a simplification for the quickstart here. You should validate the issuer. For details, 
                        // see https://github.com/Azure-Samples/active-directory-dotnet-native-aspnetcore
                        ValidateIssuer = false,

                    },
                    new OpenIdConnectSecurityTokenProvider("https://login.microsoftonline.com/common/v2.0/.well-known/openid-configuration")
                ),
            });
`

So I was kind of confused, because both these samples seem to use Microsoft Identity. I am still looking to clarify this for myself.

**Comment by multco-malan** [comment] 2019-08-02 17:13
Hello,
I am also getting the same results as ahmadizm and meticulously followed the registration/configuration steps.

I did not use the powershell automation scripts.

I followed the steps to register all 3 projects:
Register the service app (TodoListService-OBO-sample-v2)
Register the client app (TodoListClient-OBO-sample-v2)
Register the SPA app (TodoListSPA-OBO-sample-v2)
and then performed https://github.com/Azure-Samples/ms-identity-aspnet-webapi-onbehalfof#step-3--configure-the-sample-to-use-your-azure-ad-tenant configuration.

The error displayed is from line 157 in the MainWindow.xaml.cs file in the private async Task GetTodoListAsync(bool isAppStarting) method.

I cloned just this morning.

I'll try to do some more debugging next Monday, 8/5/2019.

**Comment by TiagoBrenck** [comment] 2019-08-02 21:17
@multco-malan and @ahmadizm I found two confusing steps that could be causing this problem. 

On **Step 3** you have the instruction:
`Find the app key ida:Audience...`. You should replace it with the value you got on step 2 item 8: **accept the proposed Application ID URI (api://{clientId}) by selecting Save and Continue**.

Then on **Step 3** from client, you have the instruction:
`Find the app key todo:TodoListScope...`. You should replace it with the same `api://...` value that I mentioned above, plus `/.default` at the end. 

So, two examples for these values would be:
`<add key="ida:Audience" value="api://bdf5af58-8e1d-493f-88c8-98c9c0129485"/>`
`<add key="todo:TodoListScope" value="api://bdf5af58-8e1d-493f-88c8-98c9c0129485/.default"/>`

Last but not least, I have added the step to edit the **Manifest** file for the service application. You have to set the property `knownClientApplications` with the application ids of all the apps consuming the API. Currently you cannot do it through the UI.

**Comment by TiagoBrenck** [comment] 2019-08-06 17:44
@multco-malan I believe you will face an error when you try to add a new "todo". Could you check on the service manifest file, what is the value for `knownClientApplications` property please?

**Comment by multco-malan** [comment] 2019-08-06 18:04
@TiagoBrenck 
I'm not getting any errors adding new todos:
![image](https://user-images.githubusercontent.com/29547881/62564485-c89eae80-b839-11e9-98d6-4cc37ba304a9.png)

Here is the registered service manifest section you requested:
...
"informationalUrls": {
		"termsOfService": null,
		"support": null,
		"privacy": null,
		"marketing": null
	},
	"keyCredentials": [],
	"knownClientApplications": [],
	"logoUrl": null,
	"logoutUrl": null,
	"name": "Alan-TodoListService-OBO-sample-v2",
...

**Comment by TiagoBrenck** [comment] 2019-08-06 18:33
@multco-malan one last question, did you click on the button "Grant admin consent for the directory" on Alan-TodoListService-OBO-sample-v2?

**Comment by multco-malan** [comment] 2019-08-06 18:46
@TiagoBrenck 
No I didn't and am unable to do so as I am not an admin:
![image](https://user-images.githubusercontent.com/29547881/62567332-d35c4200-b83f-11e9-976c-5ac889e933b3.png)

**Comment by TiagoBrenck** [comment] 2019-08-06 19:30
@ahmadizm did you make it work after the changes?
May I close this ticket?

**Comment by ahmadizm** [comment] 2019-08-06 19:54
Please do. I managed to make it work -- for a substantially modified/messy version. But these changes sound familiar and should address the original issue. Thank you.

**Closed** 2019-08-06 20:02 UTC
